os: linux
dist: xenial
sudo: false
language: c
compiler: gcc

addons:
    apt:
        packages:
            - doxygen
            - graphviz
            - python3-pip

before_script:
    - pip3 install --user meson

script:
    - scripts/travis-build.sh
